version: "3"
services:
  mongo:
    container_name: mongo-api-notes-container
    image: mongo:latest
    command: mongod --port 27020
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27020:27020"
  api:
    container_name: api-notes-container
    image: node:12
    working_dir: /usr/src/api-notes
    restart: always
    command: bash -c "npm install --only=prod && npm run debug"
    environment:
      - MONGO_URL=mongodb://mongo:27020/api-notes
    volumes:
      - ./dist/:/usr/src/api-notes/dist/
      - ./package.json:/usr/src/api-notes/package.json
    ports:
      - "5051:5051"
      - "9223:9223"
    links:
      - mongo
